name: TinyGPSPlus CI

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run clang-format style check
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '17'
        check-path: .
        exclude-regex: '.+.ino'

  build:
    needs: format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DBUILD_TESTING=ON

    - name: Build TinyGPSPlus
      run: cmake --build ${{github.workspace}}/build

    - name: Test TinyGPSPlus
      run: ctest --test-dir ${{github.workspace}}/build
